version: "3"
services:
#  mysql_horizon:
#   image: mysql:5.7
#   deploy:
#    placement:
#     constraints: [node.role == manager]
#   ports:
#     - 3333:3306
#   environment:
#    MYSQL_ROOT_PASSWORD: 123456
#    MYSQL_DATABASE: horizon
#    MYSQL_USER: horizon
#    MYSQL_PASSWORD: 123456
#   networks: 
#     - horizon_network
#   volumes:
#     - "./data:/var/lib/mysql"
#  phpmyadmin_horizon:
#   image: phpmyadmin/phpmyadmin
#   deploy:
#    placement:
#     constraints: [node.role == manager]
#   networks:
#    - horizon_network
#   environment:
#    PMA_HOST: mysql
#    PMA_PORT: 3306
#   ports:
#    - '8091:80'
#   volumes: 
#    - /sessions
 aplicacao_horizon:
  image: leolegends/microservices_php:stable
  # deploy:
  #  replicas: 5
  #  resources:
  #   limits:
  #    cpus: "0.1"
  #    memory: 50MB
  #  restart_policy:
  #   condition: on-failure   
  ports: 
   - 8000:80
  volumes:
   - "${DIR}:/app"
  environment:
   WEB_DOCUMENT_ROOT: /app/public
  networks:
   - horizon_network
networks: 
 horizon_network:  
